### ISSUE TITLE
The test does not work

### ISSUE THREAD

**Issue by cmjdbb** [SeongGino/QMamehook#1]
The MAMEHOOK ini file is used. The test was successful once, and then it didn't work. I don't know what was wrong.

**Comment by cmjdbb** [comment]
Enabling verbose output!
Found device @ "\\\\.\\COM1"
Assigning port no. 1
Waiting for MAME-compatible Network Output @ localhost:8000 ...
Connected to output server instance!
Detected game name!
"___empty"
Error loading file at: "C:/Users/Administrator.DESKTOP-3GPFVHF/AppData/Local/QMamehook/QMamehook/ini/___empty.ini"
"mame_stop = 1"
mame_stop signal received, disconnecting.
Detected game name!
"tha"
Loading: "C:/Users/Administrator.DESKTOP-3GPFVHF/AppData/Local/QMamehook/QMamehook/ini/tha.ini"
bool __cdecl QSerialPort::setDataTerminalReady(bool): device not open
Opened port no 1
Requested to write to port no 1 , but it's not even open yet!
"Orientation(\\\\.\\DISPLAY1) = 0"
"P1_LmpStart = 0"
"P2_LmpStart = 0"
"P1_LmpGun = 0"
"P2_LmpGun = 0"
"LmpBillboard = 0"
"P1_LmpBreak = 0"
"P2_LmpBreak = 0"
"P1_GunMotor = 0"
QIODevice::write (QSerialPort): device not open
Wrote to port no 1 , but wasn't sent in time apparently!?
"P2_GunMotor = 0"
"P1_CtmRecoil = 0"
QIODevice::write (QSerialPort): device not open
Wrote to port no 1 , but wasn't sent in time apparently!?
"P2_CtmRecoil = 0"
"P1_Life = 0"
"P2_Life = 0"
"P1_Damaged = 0"
"P2_Damaged = 0"
"Credits = 0"
"mame_stop = 1"
mame_stop signal received, disconnecting.
Detected game name!
"___empty"
Error loading file at: "C:/Users/Administrator.DESKTOP-3GPFVHF/AppData/Local/QMamehook/QMamehook/ini/___empty.ini"
Server closing, disconnecting...

**Comment by SeongGino** [comment]
I'm not sure what the "test" you're referring to even is.

That said, seems like either some other application/instance of this app has the gun's port open, or it wasn't closed properly - no other reason that it can't even establish a COM connection in the first place. Re-plugging the gun might resolve it, but I have no idea how it's in a stale state like that and there isn't much I can do about it.

I'm guessing this is on a Windows system as well, going by the paths; since I don't use Windows and there's no steps to reproduce listed, I can't provide much support for that. Only thing I can say is that closing QMamehook mid-game (while the COM port is opened and writing) won't be able to send exit/close signals, which might be the cause of the stale state - that, or your configs don't have COM port close commands.
